apiVersion: v1
kind: Service
metadata:
  name: sql-query-tool-service
spec:
  selector:
    app: sql-query-tool
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: LoadBalancer  # or NodePort for internal-only access